<?php include "/home/webpages/lima-city/rednaz/html/log.php" ?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>philipp - $title$</title>
        <link rel="stylesheet" href="/css/pandoc_syntax.css" />
        <link rel="stylesheet" href="/css/default.css" />
    </head>
    <body>
        <header>
            <div class="logo">
                <a href="/">philipp</a>
            </div>
            <nav>
                <a href="/">home</a>
                <a href="/about.php">about</a>
                <a href="/projects.php">projects</a>
            </nav>
        </header>

        <main role="main">
            <h1>$title$</h1>
            $body$
        </main>

        <footer>
            Site proudly generated by
            <a href="http://jaspervdj.be/hakyll">Hakyll</a>
        </footer>
    </body>
</html>
