<?php include "/home/webpages/lima-city/rednaz/html/log.php" ?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>philipp - about</title>
        <link rel="stylesheet" href="./css/pandoc_syntax.css" />
        <link rel="stylesheet" href="./css/default.css" />
    </head>
    <body>
        <header>
            <div class="logo">
                <a href="./">philipp</a>
            </div>
            <nav>
                <a href="./">home</a>
                <a href="./about.php">about</a>
                <a href="./projects.php">projects</a>
            </nav>
        </header>

        <main role="main">
            <h1>about</h1>
            <p>informatics master student, interested in programming languages like haskell, turning bugs into type errors, making illegal states unrepresentable</p>
<ul>
<li><a href="projects.php">projects</a></li>
<li><a href="https://www.reddit.com/user/r3dnaz">reddit</a></li>
<li><a href="https://twitter.com/r3dnaz">twitter</a></li>
<li><a href="https://gitlab.com/rdnz">gitlab</a></li>
<li><a href="https://github.com/prednaz">github</a></li>
<li><a href="https://gitlab.haskell.org/zander">gitlab.haskell.org</a></li>
<li><a href="https://www.meetup.com/haskell-utrecht/members/285900331"><em>meetup</em></a></li>
</ul>
        </main>

        <footer>
            Site proudly generated by
            <a href="http://jaspervdj.be/hakyll">Hakyll</a>
        </footer>
    </body>
</html>
