<?php include "/home/webpages/lima-city/rednaz/html/log.php" ?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>philipp - Archives</title>
        <link rel="stylesheet" href="./css/pandoc_syntax.css" />
        <link rel="stylesheet" href="./css/default.css" />
    </head>
    <body>
        <header>
            <div class="logo">
                <a href="./">philipp</a>
            </div>
            <nav>
                <a href="./">home</a>
                <a href="./about.php">about</a>
                <a href="./projects.php">projects</a>
            </nav>
        </header>

        <main role="main">
            <h1>Archives</h1>
            Here you can find all my previous posts:
<ul>
    
        <li>
            <a href="./posts/2021-03-08-gdp_talk.php">talk on Matt Noonan's Ghosts of Departed Proofs</a> - March  8, 2021
        </li>
    
        <li>
            <a href="./posts/2021-02-01-gdp.php">a trick from Matt Noonan's Ghosts of Departed Proofs</a> - February  1, 2021
        </li>
    
</ul>


        </main>

        <footer>
            Site proudly generated by
            <a href="http://jaspervdj.be/hakyll">Hakyll</a>
        </footer>
    </body>
</html>
